### PR TITLE
removed warnings.

### PR DESCRIPTION
**Pull request by ebostijancic**

### CODE REVIEW

**Comment by Dalgona** [comment]
What a surprise!

This is my first Elixir project since I started learning the language and I almost forgot this project right after the last commit. :crying_cat_face: I've never expected someone would ever look at this and now I feel somewhat pleased.

_I mean, your PR is merged. Thank you!_

**Comment by ebostijancic** [comment]
Maybe you will be more happy to hear that this library was included into a nerves firmware which got deployed on around 500 devices and worked perfectly well.

**Comment by Dalgona** [comment]
That is awesome! BTW can you tell me what version of Elixir is used to build the firmware? Maybe I could target the recent version of Elixir for further refactoring/optimization/fixes/etc...

**Comment by ebostijancic** [comment]
Currently using 1.7.3 with plans to upgrade to 1.8.1 in recent future.

**Pull request merged**
